ablog/ablog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('theblog.urls')),
    path('members/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
]

ablog/members/urls.py
from django.urls import path
from .views import UserRegisterView


urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),

]

ablog/theblog/urls.py
from django.urls import path
# from . import views
from .views import HomeView, ArticleDetailView, \
    AddPostView, UpdatePostView, DeletePostView, AddCategoryView, LikeView

urlpatterns = [
    # path('', views.home, name="home"),
    path('', HomeView.as_view(), name='home'),
    path('article/<int:pk>', ArticleDetailView.as_view(), name='article_detail'),
    path('add_post/', AddPostView.as_view(), name='add_post'),
    path('add_category/', AddCategoryView.as_view(), name='add_category'),
    path('article/edit/<int:pk>', UpdatePostView.as_view(), name='update_post'),
    path('article/<int:pk>/remove', DeletePostView.as_view(), name='delete_post'),
    path('like/<int:pk>', LikeView, name='like_post'),
]

ablog/members/models.py
from django.db import models

# Create your models here.

ablog/theblog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from datetime import date, datetime
from ckeditor.fields import RichTextField


class Category(models.Model):
    class Meta:
        verbose_name_plural = "Categories"

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        # return reverse('article_detail', args=(str(self.id)))
        return reverse('home')


class Post(models.Model):
    title = models.CharField(max_length=255)
    title_tag = models.CharField(max_length=255)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = RichTextField(blank=True, null=True)
    post_date = models.DateField(auto_now_add=True)
    category = models.CharField(max_length=255, default='Без категории')
    likes = models.ManyToManyField(User, related_name='blog_post')

    def total_likes(self):
        return self.likes.count()

    def __str__(self):
        return str(self.title) + ' | ' + str(self.author)

    def get_absolute_url(self):
        # return reverse('article_detail', args=(str(self.id)))
        return reverse('home')

ablog/theblog/forms.py
from django import forms
from .models import Post, Category

choices = Category.objects.all().values_list('name', 'name')

choice_list = []

for item in choices:
    choice_list.append(item)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'title_tag', 'author', 'category', 'body')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите заголовок'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите теги'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите описание'}),
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'title_tag', 'category', 'body')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите заголовок'}),
            'title_tag': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Введите теги'}),
            'category': forms.Select(choices=choice_list, attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Введите описание'}),
        }

ablog/members/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy


class UserRegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

ablog/theblog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Post, Category
from .forms import PostForm, EditForm
from django.urls import reverse_lazy, reverse
from django.http import HttpResponseRedirect


# def home(request):
#     return render(request, 'home.html', {})


def LikeView(request, pk):
    post = get_object_or_404(Post, id=request.POST.get('post_id'))
    post.likes.add(request.user)
    return HttpResponseRedirect(reverse('article_detail', args=[str(pk)]))


class HomeView(ListView):
    model = Post
    template_name = 'home.html'
    ordering = ['-id']
    # ordering = ['-post_date']


class ArticleDetailView(DetailView):
    model = Post
    template_name = 'article_details.html'

    def get_context_data(self, **kwargs):
        cat_menu = Category.objects.all()
        context = super(ArticleDetailView, self).get_context_data()

        stuff = get_object_or_404(Post, id=self.kwargs['pk'])
        total_likes = stuff.total_likes()
        context["cat_menu"] = cat_menu
        context["total_likes"] = total_likes
        return context


class AddPostView(CreateView):
    model = Post
    form_class = PostForm
    template_name = 'add_post.html'
    # fields = '__all__'
    # fields = ('title', 'body')


class AddCategoryView(CreateView):
    model = Category
    template_name = 'add_category.html'
    fields = '__all__'


class UpdatePostView(UpdateView):
    model = Post
    form_class = EditForm
    template_name = 'update_post.html'


class DeletePostView(DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('home')

ablog/theblog/templates/add_category.html
{% extends 'base.html' %}
{% block title %} Добавить категорию{% endblock %}
{% block content %}

{% if user.is_authenticated %}

<h1>Добавить категорию</h1>

<br><br>
<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-secondary">Добавить</button>
    </form>
</div>

{% else %}

<h1>Данная функция доступна только зарегестрированным пользователям.</h1>

{% endif %}
{% endblock %}

ablog/theblog/templates/add_post.html
{% extends 'base.html' %}
{% block title %} Создать объявление{% endblock %}
{% block content %}

{% if user.is_authenticated %}

<h1>Создать объявление</h1>

<br><br>
<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Создать</button>
    </form>
</div>

{% else %}

<h1>Данная функция доступна только зарегистрированным пользователям.</h1>

{% endif %}
{% endblock %}

ablog/theblog/templates/article_details.html
{% extends 'base.html' %}
{% block title %} {{ post.title }}  {% endblock %}
{% block content %}

<h1>{{ post.title }}</h1>
<small>
    By: {{ post.author.first_name }} {{ post.author.last_name }}
    {{post.post_date}}
    {{ post.category }}

    {% if user.is_authenticated %}

    <a href="{% url 'update_post' post.pk %}">(Изменить)</a>
    <a href="{% url 'delete_post' post.pk %}">(Удалить)</a>

    {% endif %}
</small> <br>
<hr>
<br>
{{ post.body|safe }}

<br><br>
<a href="{% url 'home' %}" class="btn btn-secondary">Назад</a>

<br><br>
<hr>
<br>
<form action="{% url 'like_post' post.pk %}" method="post">
    {% csrf_token %}
    <button type="submit" name="post_id" value="{{post.id}}"
    class="btn btn-primary">
        Мне нравится &#9829;  {{total_likes}}
    </button>
</form>

{% endblock %}

ablog/theblog/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{% block title %} {% endblock %}</title>
</head>
<body>

<style>
      body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
      }

    .shadow{
           box-shadow: 0 4px 2px -2px rgba(0,0,0,0.1);
       }
      .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
      }

     .masthead {
              background:#39b777;
              height: auto;
              padding-bottom: 15px;
              box-shadow: 0 16px 48px #E3E7EB;
              padding-top: 10px;
    }
    </style>


<nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Farmer's Market</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">

                {% if user.is_authenticated %}

                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'add_post' %}">Создать объявление</a>
                </li>
                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'add_category' %}">Добавить категорию</a>
                </li>

                <li class="nav-item text-black">
                    <a class="nav-link text-black font-weight-bold" href="{% url 'logout' %}">Выйти</a>
                </li>


                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Зарегистрироваться</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Войти</a>
                </li>

                {% endif %}

            </ul>
        </div>
    </div>
</nav>


<div class="container">
    <p>
        {% block content %}
        {% endblock %}
    </p>
</div>

    <footer class="py-3 bg-grey">
              <p class="m-0 text-dark text-center ">Copyright &copy; 2021</p>
    </footer>
<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
-->
</body>
</html>

ablog/theblog/templates/delete_post.html
{% extends 'base.html' %}
{% block title %}Удалить объявление{% endblock %}
{% block content %}

{% if user.is_authenticated %}

<h1>Удаление объявления</h1>
<br><br>
<h3>Удалить объявление «{{post.title}}»?</h3>

<br>
<div class="form-group">
    <form method="post">
        {% csrf_token %}
        <button class="btn btn-danger">Удалить</button>
    </form>
</div>

{% else %}

<h1>Данная функция доступна только зарегестрированным пользователям.</h1>

{% endif %}

{% endblock %}

ablog/theblog/templates/home.html
{% extends "base.html" %}

{% block content %}
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 17px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Добро пожаловать на Farmers Market! </h3>
                    <p class="text-light">Вы можете оставить объявления уже сегодня. &nbsp
                    </p>
                </div>
            </div>
        </div>
    </div>
    </div>
</header>

<!--<div class="container">-->
<!--    <div class="row">-->
<!--        <div class="col-sm-6">-->
<!--            {% for post in post_list %}-->
<!--            <div class="card">-->
<!--                <div class="card-body">-->
<!--                    <h2 class="card-title">{{ post.title }}</h2>-->
<!--                    <p class="card-text text-muted h6">{{ post.author }} {{ post.post_date }} </p>-->

<!--                    <p class="card-text">{{ post.body|slice:":100" }}</p>-->
<!--                    <a href="{% url 'article_detail' post.pk %}" class="btn btn-primary">Подробнее </a>-->
<!--                </div>-->

<!--            </div>-->
<!--            {% endfor %}-->
<!--        </div>-->
<!--    </div>-->


<div class="row  row-cols-10 row-cols-md-3 mx-5">
          {% for post in post_list %}
          <div class="col my-4 mx-0">
            <!-- Card Wider -->
            <div class="card h-100 card-cascade wider">

              <!-- Card image -->
              <div class="view view-cascade overlay">
                <img class="card-img-top" src="https://picsum.photos/200/100" alt="Card image cap">
                <a>
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>

              <!-- Card content -->
              <div class="card-body card-body-cascade text-center">

                <!-- Title -->
                <h4 class="card-title"><strong>{{ post.title }}</strong></h4>
                <!-- Subtitle -->
                <h5 class="blue-text pb-2"><strong>{{ post.category }}</strong></h5>
                <!-- Text -->
                <p class="card-text">{{ post.body|truncatechars:100 }}</p>
<!--                <p class="card-text">{{ item.price }}</p>-->

                <!-- Button -->

<!--                <a class="btn btn-secondary btn-md btn-rounded mt-5 teal accent-2">Купить</a>-->
                <a class="btn btn-secondary btn-md btn-rounded mt-5" href="{% url 'article_detail' post.pk %}">Подробнее &rarr;</a>

              </div>

            </div>
            <!-- Card Wider -->
          </div>
          {% endfor %}


        </div>

<!--<div class="container-fluid">-->
<!--    <div class="row row-cols-3 g-4">-->
<!--        {% for post in post_list %}-->
<!--        <div class="col rounded border border-light mt-3 ml-3 shadow">-->
<!--            <div class="card h-100">-->
<!--                <img src="https://picsum.photos/300/200" class="card-img-top"-->
<!--                     style="max-width: 300px;max-height: 300px;width: auto;height: auto;margin: auto;">-->
<!--                <p class="card-text">{{post.title}}</p>-->
<!--                <p class="card-text">{{ post.body|safe|slice:":200" }}</p>-->
<!--                <a href="#">Подробнее</a>-->
<!--            </div>-->
<!--        </div>-->
<!--        {% if forloop.counter|divisibleby:3 %}-->
<!--    </div>-->
<!--    <div class="row">-->
<!--        {% endif %}-->
<!--        {% endfor %}-->
<!--    </div>-->
</div>

{%endblock%}

ablog/theblog/templates/update_post.html
{% extends 'base.html' %}
{% block title %}Изменить объявление{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<h1>Изменить объявление</h1>

<br><br>
<div class="form-group">
    <form method="post">
        {% csrf_token %}
        {{ form.media }}
        {{ form.as_p }}
        <button class="btn btn-secondary">Изменить</button>
    </form>
</div>

{% else %}

<h1>Данная функция доступна только зарегестрированным пользователям.</h1>

{% endif %}

{% endblock %}